# Generated by Django 4.2.5 on 2023-09-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_credentials_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudlogin',
            name='user',
        ),
    ]
